"""Generate build-ws.cmd: drive cl.exe and link.exe directly for this plugin.

CMake is the supported path (see README), but it can hang in restricted environments while probing the
compiler - it needs to capture a child process's output, which some sandboxes deny. This script writes a batch
file that compiles and links the plugin straight, and it is the path this repository was developed with.

    python tools/gen_build.py
    build-ws.cmd playeraim        (or just build-ws.cmd)
"""
from __future__ import annotations

import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COMMON = ['common/host.cpp', 'common/memory.cpp', 'common/patch.cpp', 'common/seat.cpp']


def sources(path, target):
    """The source list of add_library(<target> SHARED ...) in a CMakeLists, resolved against that directory."""
    with open(os.path.join(ROOT, path), encoding='utf-8') as f:
        text = f.read()
    text = '\n'.join(l for l in text.split('\n') if not l.strip().startswith('#'))
    m = re.search(r'add_library\(\s*' + re.escape(target) + r'\s+SHARED\s+(.*?)\)', text, re.S)
    if not m:
        raise SystemExit(f'add_library({target} SHARED ...) not found in {path}')
    anchor = os.path.dirname(path)
    out = []
    for token in m.group(1).split():
        token = token.strip()
        if not token or token.startswith('$'):
            continue
        out.append(os.path.normpath(os.path.join(anchor, token)).replace('/', '\\'))
    return out


def main():
    pa_src = sources('plugin/CMakeLists.txt', 'EDF6PlayerAim')
    rows = []
    w = rows.append

    w('@echo off')
    w('setlocal')
    w('rem Generated by tools/gen_build.py - compiles the plugin with cl.exe/link.exe directly.')
    w('set "ROOT=%~dp0."')
    w('set "OUT=%ROOT%\\build\\Mods\\Plugins"')
    w('set "OBJ=%ROOT%\\build\\obj"')
    w('if not exist "%OUT%" mkdir "%OUT%"')
    w('if not exist "%OBJ%" mkdir "%OBJ%"')
    w('set "LOG=%ROOT%\\build\\build.log"')
    w('set WHICH=%~1')
    w('if "%WHICH%"=="" set WHICH=playeraim')
    w('')
    w('rem ---- locate the toolchain ----')
    w('set "VS="')
    w('for /f "usebackq tokens=*" %%i in (`"%ProgramFiles(x86)%\\Microsoft Visual Studio\\Installer\\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do set "VS=%%i"')
    w('if not defined VS set "VS=C:\\BuildTools"')
    w('call "%VS%\\VC\\Auxiliary\\Build\\vcvars64.bat" >nul 2>&1')
    w('if errorlevel 1 (echo vcvars64.bat failed - is the C++ toolchain installed? & exit /b 1)')
    w('')
    w('set "INC=/I"%ROOT%\\common" /I"%ROOT%\\third_party\\EDFModLoader""')
    w('set "CFLAGS=/nologo /std:c++17 /EHsc /W4 /WX /utf-8 /permissive- /O2 /MT /DNDEBUG /c"')
    w('')
    w(':playeraim')
    common_objs = []
    for i, src in enumerate(COMMON):
        obj = f'common{i}.obj'
        common_objs.append('%OBJ%\\' + obj)
        w(f'cl %CFLAGS% %INC% /Fo"%OBJ%\\{obj}" "%ROOT%\\{src}" >>"%LOG%" 2>&1 || (echo COMPILE FAILED {src} & type "%LOG%" & exit /b 1)')
    pa_objs = list(common_objs)
    for i, src in enumerate(pa_src):
        obj = f'playeraim{i}.obj'
        pa_objs.append('%OBJ%\\' + obj)
        w(f'cl %CFLAGS% %INC% /Fo"%OBJ%\\{obj}" "%ROOT%\\{src}" >>"%LOG%" 2>&1 || (echo COMPILE FAILED {src} & type "%LOG%" & exit /b 1)')
    w('link /nologo /DLL /DYNAMICBASE /NXCOMPAT /PDBALTPATH:EDF6PlayerAim.pdb '
      '/OUT:"%OUT%\\EDF6PlayerAim.dll" /PDB:"%OUT%\\EDF6PlayerAim.pdb" ' + ' '.join(pa_objs) + ' >>"%LOG%" 2>&1 || (echo LINK FAILED & type "%LOG%" & exit /b 1)')
    w('copy /y "%ROOT%\\plugin\\EDF6PlayerAim.ini" "%OUT%\\EDF6PlayerAim.ini" >nul')
    w('echo built EDF6PlayerAim.dll')

    out = os.path.join(ROOT, 'build-ws.cmd')
    with open(out, 'w', encoding='utf-8', newline='\r\n') as f:
        f.write('\n'.join(rows) + '\n')
    print(f'wrote {out}: playeraim {len(pa_src)} sources (+{len(COMMON)} common)')


if __name__ == '__main__':
    main()
